name: &project_name ${COMPOSE_PROJECT_NAME}

services:
  rustfs:
    image: rustfs/rustfs:${RUSTFS_VERSION}@${RUSTFS_DIGEST}
    container_name: *project_name
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_ACCESS_KEY_FILE: /run/secrets/access_key
      RUSTFS_SECRET_KEY_FILE: /run/secrets/secret_key
      RUSTFS_OBS_LOGGER_LEVEL: ${RUSTFS_OBS_LOGGER_LEVEL}
      RUSTFS_OBS_LOG_DIRECTORY: ""
      RUSTFS_TLS_PATH: /run/secrets
      RUSTFS_REGION: eu-west-3
      RUSTFS_OBJECT_CACHE_ENABLE: "true"
      RUSTFS_OBJECT_CACHE_TTL_SECS: 300
    secrets:
      - access_key
      - secret_key
    volumes:
      - data:/data
      - logs:/app/logs
      - ${TLS_KEY}:/run/secrets/rustfs_key.pem:ro,z
      - ${TLS_CERT}:/run/secrets/rustfs_cert.pem:ro,z
    restart: ${RESTART_POLICY}
    healthcheck:
      test: |
        curl -fk https://127.0.0.1:9000/health \
          && curl -fk https://127.0.0.1:9001/rustfs/console/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 10s

secrets:
  access_key:
    environment: "AWS_ACCESS_KEY_ID"
  secret_key:
    environment: "AWS_SECRET_ACCESS_KEY"

networks:
  default:
    name: *project_name
    driver: bridge
    enable_ipv6: true

volumes:
  data:
  logs:
